package com.jach.minutra.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _AppProperties was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AppProperties extends CayenneDataObject {

    public static final String ENVIRONMENT_PROPERTY = "environment";
    public static final String PROP_KEY_PROPERTY = "propKey";
    public static final String PROP_VALUE_PROPERTY = "propValue";

    public static final String ID_PK_COLUMN = "id";

    public void setEnvironment(Integer environment) {
        writeProperty(ENVIRONMENT_PROPERTY, environment);
    }
    public Integer getEnvironment() {
        return (Integer)readProperty(ENVIRONMENT_PROPERTY);
    }

    public void setPropKey(String propKey) {
        writeProperty(PROP_KEY_PROPERTY, propKey);
    }
    public String getPropKey() {
        return (String)readProperty(PROP_KEY_PROPERTY);
    }

    public void setPropValue(String propValue) {
        writeProperty(PROP_VALUE_PROPERTY, propValue);
    }
    public String getPropValue() {
        return (String)readProperty(PROP_VALUE_PROPERTY);
    }

}
