package com.jach.minutra.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.MinuteTaskTypes;
import com.jach.minutra.model.Minutes;
import com.jach.minutra.model.Users;

/**
 * Class _MinuteTasks was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MinuteTasks extends CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DUE_DATE_PROPERTY = "dueDate";
    public static final String IS_DONE_PROPERTY = "isDone";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String TO_MINUTE_TASK_TYPES_PROPERTY = "toMinuteTaskTypes";
    public static final String TO_MINUTES_PROPERTY = "toMinutes";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_PK_COLUMN = "id";

    public void setCreationDate(Date creationDate) {
        writeProperty(CREATION_DATE_PROPERTY, creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty(CREATION_DATE_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setDueDate(Date dueDate) {
        writeProperty(DUE_DATE_PROPERTY, dueDate);
    }
    public Date getDueDate() {
        return (Date)readProperty(DUE_DATE_PROPERTY);
    }

    public void setIsDone(Boolean isDone) {
        writeProperty(IS_DONE_PROPERTY, isDone);
    }
    public Boolean getIsDone() {
        return (Boolean)readProperty(IS_DONE_PROPERTY);
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty(MODIFICATION_DATE_PROPERTY, modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty(MODIFICATION_DATE_PROPERTY);
    }

    public void setToMinuteTaskTypes(MinuteTaskTypes toMinuteTaskTypes) {
        setToOneTarget(TO_MINUTE_TASK_TYPES_PROPERTY, toMinuteTaskTypes, true);
    }

    public MinuteTaskTypes getToMinuteTaskTypes() {
        return (MinuteTaskTypes)readProperty(TO_MINUTE_TASK_TYPES_PROPERTY);
    }


    public void setToMinutes(Minutes toMinutes) {
        setToOneTarget(TO_MINUTES_PROPERTY, toMinutes, true);
    }

    public Minutes getToMinutes() {
        return (Minutes)readProperty(TO_MINUTES_PROPERTY);
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget(TO_USERS_PROPERTY, toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty(TO_USERS_PROPERTY);
    }


}
