package com.jach.minutra.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.MinuteDocuments;
import com.jach.minutra.model.MinuteMembers;
import com.jach.minutra.model.MinuteTasks;
import com.jach.minutra.model.Users;

/**
 * Class _Minutes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Minutes extends CayenneDataObject {

    public static final String AGENDA_PROPERTY = "agenda";
    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String FROM_DATE_PROPERTY = "fromDate";
    public static final String LOCATION_PROPERTY = "location";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String TITLE_PROPERTY = "title";
    public static final String TO_DATE_PROPERTY = "toDate";
    public static final String MINUTE_DOCUMENTS_ARRAY_PROPERTY = "minuteDocumentsArray";
    public static final String MINUTE_MEMBERS_ARRAY_PROPERTY = "minuteMembersArray";
    public static final String MINUTE_TASKS_ARRAY_PROPERTY = "minuteTasksArray";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_PK_COLUMN = "id";

    public void setAgenda(String agenda) {
        writeProperty(AGENDA_PROPERTY, agenda);
    }
    public String getAgenda() {
        return (String)readProperty(AGENDA_PROPERTY);
    }

    public void setCreationDate(Date creationDate) {
        writeProperty(CREATION_DATE_PROPERTY, creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty(CREATION_DATE_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setFromDate(Date fromDate) {
        writeProperty(FROM_DATE_PROPERTY, fromDate);
    }
    public Date getFromDate() {
        return (Date)readProperty(FROM_DATE_PROPERTY);
    }

    public void setLocation(String location) {
        writeProperty(LOCATION_PROPERTY, location);
    }
    public String getLocation() {
        return (String)readProperty(LOCATION_PROPERTY);
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty(MODIFICATION_DATE_PROPERTY, modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty(MODIFICATION_DATE_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setToDate(Date toDate) {
        writeProperty(TO_DATE_PROPERTY, toDate);
    }
    public Date getToDate() {
        return (Date)readProperty(TO_DATE_PROPERTY);
    }

    public void addToMinuteDocumentsArray(MinuteDocuments obj) {
        addToManyTarget(MINUTE_DOCUMENTS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMinuteDocumentsArray(MinuteDocuments obj) {
        removeToManyTarget(MINUTE_DOCUMENTS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MinuteDocuments> getMinuteDocumentsArray() {
        return (List<MinuteDocuments>)readProperty(MINUTE_DOCUMENTS_ARRAY_PROPERTY);
    }


    public void addToMinuteMembersArray(MinuteMembers obj) {
        addToManyTarget(MINUTE_MEMBERS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMinuteMembersArray(MinuteMembers obj) {
        removeToManyTarget(MINUTE_MEMBERS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MinuteMembers> getMinuteMembersArray() {
        return (List<MinuteMembers>)readProperty(MINUTE_MEMBERS_ARRAY_PROPERTY);
    }


    public void addToMinuteTasksArray(MinuteTasks obj) {
        addToManyTarget(MINUTE_TASKS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMinuteTasksArray(MinuteTasks obj) {
        removeToManyTarget(MINUTE_TASKS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MinuteTasks> getMinuteTasksArray() {
        return (List<MinuteTasks>)readProperty(MINUTE_TASKS_ARRAY_PROPERTY);
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget(TO_USERS_PROPERTY, toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty(TO_USERS_PROPERTY);
    }


}
