package com.jach.minutra.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.MinuteTasks;

/**
 * Class _MinuteTaskTypes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MinuteTaskTypes extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String MINUTE_TASKS_ARRAY_PROPERTY = "minuteTasksArray";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToMinuteTasksArray(MinuteTasks obj) {
        addToManyTarget(MINUTE_TASKS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMinuteTasksArray(MinuteTasks obj) {
        removeToManyTarget(MINUTE_TASKS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MinuteTasks> getMinuteTasksArray() {
        return (List<MinuteTasks>)readProperty(MINUTE_TASKS_ARRAY_PROPERTY);
    }


}
