package com.jach.minutra.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.UserRoles;

/**
 * Class _Roles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Roles extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String USER_ROLES_ARRAY_PROPERTY = "userRolesArray";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToUserRolesArray(UserRoles obj) {
        addToManyTarget(USER_ROLES_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromUserRolesArray(UserRoles obj) {
        removeToManyTarget(USER_ROLES_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UserRoles> getUserRolesArray() {
        return (List<UserRoles>)readProperty(USER_ROLES_ARRAY_PROPERTY);
    }


}
