package com.jach.minutra.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.SummaryDocuments;
import com.jach.minutra.model.SummaryMembers;
import com.jach.minutra.model.SummaryTasks;
import com.jach.minutra.model.Users;

/**
 * Class _Summaries was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Summaries extends CayenneDataObject {

    public static final String AGENDA_PROPERTY = "agenda";
    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String FROM_DATE_PROPERTY = "fromDate";
    public static final String LOCATION_PROPERTY = "location";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String TITLE_PROPERTY = "title";
    public static final String TO_DATE_PROPERTY = "toDate";
    public static final String SUMMARY_DOCUMENTS_ARRAY_PROPERTY = "summaryDocumentsArray";
    public static final String SUMMARY_MEMBERS_ARRAY_PROPERTY = "summaryMembersArray";
    public static final String SUMMARY_TASKS_ARRAY_PROPERTY = "summaryTasksArray";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_PK_COLUMN = "id";

    public void setAgenda(String agenda) {
        writeProperty(AGENDA_PROPERTY, agenda);
    }
    public String getAgenda() {
        return (String)readProperty(AGENDA_PROPERTY);
    }

    public void setCreationDate(Date creationDate) {
        writeProperty(CREATION_DATE_PROPERTY, creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty(CREATION_DATE_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setFromDate(Date fromDate) {
        writeProperty(FROM_DATE_PROPERTY, fromDate);
    }
    public Date getFromDate() {
        return (Date)readProperty(FROM_DATE_PROPERTY);
    }

    public void setLocation(String location) {
        writeProperty(LOCATION_PROPERTY, location);
    }
    public String getLocation() {
        return (String)readProperty(LOCATION_PROPERTY);
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty(MODIFICATION_DATE_PROPERTY, modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty(MODIFICATION_DATE_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setToDate(Date toDate) {
        writeProperty(TO_DATE_PROPERTY, toDate);
    }
    public Date getToDate() {
        return (Date)readProperty(TO_DATE_PROPERTY);
    }

    public void addToSummaryDocumentsArray(SummaryDocuments obj) {
        addToManyTarget(SUMMARY_DOCUMENTS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSummaryDocumentsArray(SummaryDocuments obj) {
        removeToManyTarget(SUMMARY_DOCUMENTS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SummaryDocuments> getSummaryDocumentsArray() {
        return (List<SummaryDocuments>)readProperty(SUMMARY_DOCUMENTS_ARRAY_PROPERTY);
    }


    public void addToSummaryMembersArray(SummaryMembers obj) {
        addToManyTarget(SUMMARY_MEMBERS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSummaryMembersArray(SummaryMembers obj) {
        removeToManyTarget(SUMMARY_MEMBERS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SummaryMembers> getSummaryMembersArray() {
        return (List<SummaryMembers>)readProperty(SUMMARY_MEMBERS_ARRAY_PROPERTY);
    }


    public void addToSummaryTasksArray(SummaryTasks obj) {
        addToManyTarget(SUMMARY_TASKS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSummaryTasksArray(SummaryTasks obj) {
        removeToManyTarget(SUMMARY_TASKS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SummaryTasks> getSummaryTasksArray() {
        return (List<SummaryTasks>)readProperty(SUMMARY_TASKS_ARRAY_PROPERTY);
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget(TO_USERS_PROPERTY, toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty(TO_USERS_PROPERTY);
    }


}
