package com.jach.minutra.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.SummaryTasks;

/**
 * Class _SummaryTaskTypes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SummaryTaskTypes extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String SUMMARY_TASKS_ARRAY_PROPERTY = "summaryTasksArray";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToSummaryTasksArray(SummaryTasks obj) {
        addToManyTarget(SUMMARY_TASKS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSummaryTasksArray(SummaryTasks obj) {
        removeToManyTarget(SUMMARY_TASKS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SummaryTasks> getSummaryTasksArray() {
        return (List<SummaryTasks>)readProperty(SUMMARY_TASKS_ARRAY_PROPERTY);
    }


}
