package com.jach.minutra.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.jach.minutra.model.Summaries;
import com.jach.minutra.model.SummaryTaskTypes;
import com.jach.minutra.model.Users;

/**
 * Class _SummaryTasks was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SummaryTasks extends CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DETAIL_PROPERTY = "detail";
    public static final String DUE_DATE_PROPERTY = "dueDate";
    public static final String IS_DONE_PROPERTY = "isDone";
    public static final String MODIFICATION_DATE_PROPERTY = "modificationDate";
    public static final String TO_SUMMARIES_PROPERTY = "toSummaries";
    public static final String TO_SUMMARY_TASK_TYPES_PROPERTY = "toSummaryTaskTypes";
    public static final String TO_USERS_PROPERTY = "toUsers";

    public static final String ID_PK_COLUMN = "id";

    public void setCreationDate(Date creationDate) {
        writeProperty(CREATION_DATE_PROPERTY, creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty(CREATION_DATE_PROPERTY);
    }

    public void setDetail(String detail) {
        writeProperty(DETAIL_PROPERTY, detail);
    }
    public String getDetail() {
        return (String)readProperty(DETAIL_PROPERTY);
    }

    public void setDueDate(Date dueDate) {
        writeProperty(DUE_DATE_PROPERTY, dueDate);
    }
    public Date getDueDate() {
        return (Date)readProperty(DUE_DATE_PROPERTY);
    }

    public void setIsDone(Boolean isDone) {
        writeProperty(IS_DONE_PROPERTY, isDone);
    }
    public Boolean getIsDone() {
        return (Boolean)readProperty(IS_DONE_PROPERTY);
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty(MODIFICATION_DATE_PROPERTY, modificationDate);
    }
    public Date getModificationDate() {
        return (Date)readProperty(MODIFICATION_DATE_PROPERTY);
    }

    public void setToSummaries(Summaries toSummaries) {
        setToOneTarget(TO_SUMMARIES_PROPERTY, toSummaries, true);
    }

    public Summaries getToSummaries() {
        return (Summaries)readProperty(TO_SUMMARIES_PROPERTY);
    }


    public void setToSummaryTaskTypes(SummaryTaskTypes toSummaryTaskTypes) {
        setToOneTarget(TO_SUMMARY_TASK_TYPES_PROPERTY, toSummaryTaskTypes, true);
    }

    public SummaryTaskTypes getToSummaryTaskTypes() {
        return (SummaryTaskTypes)readProperty(TO_SUMMARY_TASK_TYPES_PROPERTY);
    }


    public void setToUsers(Users toUsers) {
        setToOneTarget(TO_USERS_PROPERTY, toUsers, true);
    }

    public Users getToUsers() {
        return (Users)readProperty(TO_USERS_PROPERTY);
    }


}
